server:
  port: 8888
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8080
          predicates:
            - Path=/user-service/**

springdoc:
  swagger-ui:
    urls:
      - name: user-service (via gateway)
        url: /user-service/v3/api-docs
      - name: user-service (direct 8080)
        url: http://localhost:8080/user-service/v3/api-docs