server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  security:
    user:
      name: admin
      password: 123456
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://${USER_SERVICE_HOST:localhost}:8080
          predicates:
            - >-
              Path=${app.api-prefix}/users/**,
              ${app.api-prefix}/auth/**
          filters:
            - StripPrefix=2

        - id: user-service-doc
          uri: http://${USER_SERVICE_HOST:localhost}:8080
          predicates:
            - >-
              Path=${app.api-prefix}/user-service/v3/api-docs/**
          filters:
            - StripPrefix=3

        - id: payment-service
          uri: http://${PAYMENT_SERVICE_HOST:localhost}:8081
          predicates:
            - >-
              Path=${app.api-prefix}/transactions/**
          filters:
            - StripPrefix=2

        - id: payment-service-doc
          uri: http://${PAYMENT_SERVICE_HOST:localhost}:8081
          predicates:
            - >-
              Path=${app.api-prefix}/payment-service/v3/api-docs/**
          filters:
            - StripPrefix=3

        - id: ticket-service
          uri: http://${TICKET_SERVICE_HOST:localhost}:8082
          predicates:
            - >-
              Path=${app.api-prefix}/ticket-types/**,
              ${app.api-prefix}/dynamic-prices/**
          filters:
            - StripPrefix=2

        - id: ticket-service-doc
          uri: http://${TICKET_SERVICE_HOST:localhost}:8082
          predicates:
            - >-
              Path=${app.api-prefix}/ticket-service/v3/api-docs/**
          filters:
            - StripPrefix=3

        - id: notification-service
          uri: http://${NOTIFICATION_SERVICE_HOST:localhost}:8083
          predicates:
            - >-
              Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=2

        - id: notification-service-doc
          uri: http://${NOTIFICATION_SERVICE_HOST:localhost}:8083
          predicates:
            - >-
              Path=${app.api-prefix}/notification-service/v3/api-docs/**
          filters:
            - StripPrefix=3

        - id: route-service
          uri: http://${ROUTE_SERVICE_HOST:localhost}:8084
          predicates:
            - >-
              Path=${app.api-prefix}/bus-routes/**,
              ${app.api-prefix}/stations/**,
              ${app.api-prefix}/lines/**,
              ${app.api-prefix}/line-segments/**
          filters:
            - StripPrefix=2

        - id: route-service-doc
          uri: http://${ROUTE_SERVICE_HOST:localhost}:8084
          predicates:
            - >-
              Path=${app.api-prefix}/route-service/v3/api-docs/**
          filters:
            - StripPrefix=3

        - id: content-service
          uri: http://${CONTENT_SERVICE_HOST:localhost}:8085
          predicates:
            - >-
              Path=${app.api-prefix}/contents/**,
              ${app.api-prefix}/content-images/**
          filters:
            - StripPrefix=2

        - id: content-service-doc
          uri: http://${CONTENT_SERVICE_HOST:localhost}:8085
          predicates:
            - >-
              Path=${app.api-prefix}/content-service/v3/api-docs/**
          filters:
            - StripPrefix=3

        - id: order-service
          uri: http://${ORDER_SERVICE_HOST:localhost}:8086
          predicates:
            - >-
              Path=${app.api-prefix}/ticket-orders/**
          filters:
            - StripPrefix=2

        - id: order-service-doc
          uri: http://${ORDER_SERVICE_HOST:localhost}:8086
          predicates:
            - >-
              Path=${app.api-prefix}/order-service/v3/api-docs/**
          filters:
            - StripPrefix=3

        - id: scanner-service
          uri: http://${SCANNER_SERVICE_HOST:localhost}:8087
          predicates:
            - >-
              Path=${app.api-prefix}/scanner/**
          filters:
            - StripPrefix=2

        - id: scanner-service-doc
          uri: http://${SCANNER_SERVICE_HOST:localhost}:8087
          predicates:
            - >-
              Path=${app.api-prefix}/scanner-service/v3/api-docs/**
          filters:
            - StripPrefix=3

springdoc:
  swagger-ui:
    urls:
      # qua gateway
      - name: user-service (via gateway)
        url: ${app.api-prefix}/user-service/v3/api-docs
      - name: payment-service (via gateway)
        url: ${app.api-prefix}/payment-service/v3/api-docs
      - name: ticket-service (via gateway)
        url: ${app.api-prefix}/ticket-service/v3/api-docs
      - name: notification-service (via gateway)
        url: ${app.api-prefix}/notification-service/v3/api-docs
      - name: route-service (via gateway)
        url: ${app.api-prefix}/route-service/v3/api-docs
      - name: content-service (via gateway)
        url: ${app.api-prefix}/content-service/v3/api-docs
      - name: order-service (via gateway)
        url: ${app.api-prefix}/order-service/v3/api-docs
      - name: scanner-service (via gateway)
        url: ${app.api-prefix}/scanner-service/v3/api-docs

      # direct (cho local)
      - name: user-service (direct)
        url: http://localhost:8080/v3/api-docs
      - name: payment-service (direct)
        url: http://localhost:8081/v3/api-docs
      - name: ticket-service (direct)
        url: http://localhost:8082/v3/api-docs
      - name: notification-service (direct)
        url: http://localhost:8083/v3/api-docs
      - name: route-service (direct)
        url: http://localhost:8084/v3/api-docs
      - name: content-service (direct)
        url: http://localhost:8085/v3/api-docs
      - name: order-service (direct)
        url: http://localhost:8086/v3/api-docs
      - name: scanner-service (direct)
        url: http://localhost:8087/v3/api-docs
