server:
  port: 8888
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8080
          predicates:
            - Path=/user-service/**

springdoc:
  api-docs:
    path: /v3/api-docs        # endpoint sinh JSON OpenAPI (mặc định là /v3/api-docs)
  swagger-ui:
    path: /swagger-ui/index.html   # truy cập UI tại /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha
    urls:
      - name: user-service
        url: /user-service/v3/api-docs
