server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8080
          predicates:
            - >-
              Path=${app.api-prefix}/users/**,
              ${app.api-prefix}/auth/**
          filters:
            - StripPrefix=2

        - id: user-service-doc
          uri: http://user-service:8080
          predicates:
            - >-
              Path=${app.api-prefix}/user-service/v3/api-docs/**
          filters:
            - StripPrefix=3

        - id: payment-service
          uri: http://payment-service:8081
          predicates:
            - >-
              Path=${app.api-prefix}/transactions/**
          filters:
            - StripPrefix=2

        - id: payment-service-doc
          uri: http://payment-service:8081
          predicates:
            - >-
              Path=${app.api-prefix}/payment-service/v3/api-docs/**
          filters:
            - StripPrefix=3

        - id: ticket-service
          uri: http://ticket-service:8082
          predicates:
            - >-
              Path=${app.api-prefix}/ticket-types/**,
              ${app.api-prefix}/dynamic-prices/**
          filters:
            - StripPrefix=2

        - id: ticket-service-doc
          uri: http://ticket-service:8082
          predicates:
            - >-
              Path=${app.api-prefix}/ticket-service/v3/api-docs/**
          filters:
            - StripPrefix=3

        - id: notification-service
          uri: http://notification-service:8083
          predicates:
            - >-
              Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=2

        - id: notification-service-doc
          uri: http://notification-service:8083
          predicates:
            - >-
              Path=${app.api-prefix}/notification-service/v3/api-docs/**
          filters:
            - StripPrefix=3

        - id: route-service
          uri: http://route-service:8084
          predicates:
            - >-
              Path=${app.api-prefix}/bus-routes/**,
              ${app.api-prefix}/stations/**,
              ${app.api-prefix}/lines/**,
              ${app.api-prefix}/line-segments/**
          filters:
            - StripPrefix=2

        - id: route-service-doc
          uri: http://route-service:8084
          predicates:
            - >-
              Path=${app.api-prefix}/route-service/v3/api-docs/**
          filters:
            - StripPrefix=3

        - id: content-service
          uri: http://content-service:8085
          predicates:
            - >-
              Path=${app.api-prefix}/contents/**,
              ${app.api-prefix}/content-images/**
          filters:
            - StripPrefix=2

        - id: content-service-doc
          uri: http://content-service:8085
          predicates:
            - >-
              Path=${app.api-prefix}/content-service/v3/api-docs/**
          filters:
            - StripPrefix=3

        - id: order-service
          uri: http://order-service:8086
          predicates:
            - >-
              Path=${app.api-prefix}/ticket-orders/**
          filters:
            - StripPrefix=2

        - id: order-service-doc
          uri: http://order-service:8086
          predicates:
            - >-
              Path=${app.api-prefix}/order-service/v3/api-docs/**
          filters:
            - StripPrefix=3

        - id: scanner-service
          uri: http://scanner-service:8087
          predicates:
            - >-
              Path=${app.api-prefix}/scanner/**
          filters:
            - StripPrefix=2

        - id: scanner-service-doc
          uri: http://scanner-service:8087
          predicates:
            - >-
              Path=${app.api-prefix}/scanner-service/v3/api-docs/**
          filters:
            - StripPrefix=3
