server:
  port: 8081
  servlet:
    context-path: /payment
spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://localhost:3306/payment_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: admin
      password: 123456
  jwt:
    signerKey: ${JWT_SIGNER_KEY}
    valid-duration: 3600 # in seconds
    refreshable-duration: 36000 # in seconds
  openapi:
    service:
      api-docs: SAT-BACKEND API
      server: http://localhost:8081
      title: SAT-BACKEND
      version: 1.0.0
  springdoc:
    swagger-ui:
      enabled: true