server:
  port: 8081
spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://localhost:3306/payment_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: admin
      password: 123456
  jwt:
    signerKey: ${JWT_SIGNER_KEY}
    valid-duration: 3600 # in seconds
    refreshable-duration: 36000 # in seconds
  openapi:
    service:
      api-docs: SAT-BACKEND API
      server: http://localhost:8081
      title: SAT-BACKEND
      version: 1.0.0
  springdoc:
    swagger-ui:
      enabled: true

payment:
  vnPay:
    url: ${PAY_URL}
    tmnCode: ${TMN_CODE}
    secretKey: ${SECRET_KEY}
    returnUrl: ${RETURN_URL}
    version: ${VERSION}
    command: ${COMMAND}
    orderType: ${ORDER_TYPE}

app:
  services:
    ticket_order:
      url: http://localhost:8086
    user:
      url: http://localhost:8080