server:
  port: 8080
  servlet:
    context-path: /user-service
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: admin
      password: 123456
jwt:
  signerKey: ${JWT_SIGNER_KEY}
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds
openapi:
  service:
    api-docs: SAT-BACKEND API
    server: http://localhost:8080
    title: SAT-BACKEND
    version: 1.0.0
springdoc:
  swagger-ui:
    enabled: true





