server:
  port: 8080
spring:
  application:
    name: user-service
  datasource:
#    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME}
    url: jdbc:mysql://localhost:3306/metro

    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: ${DB_USERNAME}
    username: root
    password: root

#    password: ${DB_PASSWORD}
#    jdbc:mysql://localhost:3306/metro
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: admin
      password: 123456
jwt:
  signerKey: ${JWT_SIGNER_KEY}
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html





