server:
  port: 8086
spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/order_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: admin
      password: 123456
  jwt:
    signerKey: ${JWT_SIGNER_KEY}
    valid-duration: 3600 # in seconds
    refreshable-duration: 36000 # in seconds
  openapi:
    service:
      api-docs: SAT-BACKEND API
      server: http://localhost:8086
      title: SAT-BACKEND
      version: 1.0.0
  springdoc:
    swagger-ui:
      enabled: true
app:
  services:
    user:
      url: http://localhost:8080
    ticket:
      url: http://localhost:8082