spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

# Nếu bạn dùng Flyway hoặc Liquibase, vô hiệu hoá lúc test
# flyway:
#   enabled: false
# liquibase:
#   enabled: false
