server:
  port: 8082
  servlet:
    context-path: /ticket
spring:
  application:
    name: ticket-service
  datasource:
    url: jdbc:mysql://localhost:3306/ticket_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: admin
      password: 123456
  jwt:
    signerKey: ${JWT_SIGNER_KEY}
    valid-duration: 3600 # in seconds
    refreshable-duration: 36000 # in seconds
  openapi:
    service:
      api-docs: SAT-BACKEND API
      server: http://localhost:8082
      title: SAT-BACKEND
      version: 1.0.0
  springdoc:
    swagger-ui:
      enabled: true